services:
  db:
    image: postgres:16
    container_name: booking_db
    env_file:
      - .env_not_dev

  redis:
    image: redis:7-alpine
    container_name: booking_cache
    env_file:
      - .env_not_dev
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}

  booking:
    build:
      context: .
    container_name: booking_app
    env_file:
      - .env_not_dev
    depends_on:
      - db
      - redis
    command: ["/booking/docker/app.sh"]
    ports:
      - 1488:8000

