version: '3.9'

services:
  db:
    image: postgres:16
    restart: always
    shm_size: 128mb
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U depich -d fastshumeiko"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis: # <-- Новый сервис Redis
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./redis_data:/data:Z
    command: redis-server --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
  redis_data: