"""hz

Revision ID: 6916aae7b8c3
Revises: ed0529570c5d
Create Date: 2025-03-26 23:13:04.567319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6916aae7b8c3'
down_revision: Union[str, None] = 'ed0529570c5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotels', 'rooms_quantity')
    op.add_column('landlords', sa.Column('password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('landlords', 'password')
    op.add_column('hotels', sa.Column('rooms_quantity', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
