"""Last modified tables)

Revision ID: f49d9ab3d637
Revises: 6d8db84f8e01
Create Date: 2025-03-24 17:45:06.147653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f49d9ab3d637'
down_revision: Union[str, None] = '6d8db84f8e01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('location', sa.String(), nullable=False))
    op.add_column('hotels', sa.Column('services', sa.JSON(), nullable=False))
    op.add_column('hotels', sa.Column('rooms_quantity', sa.Integer(), nullable=False))
    op.add_column('hotels', sa.Column('image_id', sa.Integer(), nullable=False))
    op.drop_column('hotels', 'stars')
    op.drop_column('hotels', 'address')
    op.add_column('rooms', sa.Column('name', sa.String(), nullable=False))
    op.add_column('rooms', sa.Column('description', sa.String(), nullable=False))
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_column('rooms', 'description')
    op.drop_column('rooms', 'name')
    op.add_column('hotels', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('hotels', sa.Column('stars', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('hotels', 'image_id')
    op.drop_column('hotels', 'rooms_quantity')
    op.drop_column('hotels', 'services')
    op.drop_column('hotels', 'location')
    # ### end Alembic commands ###
